# Generated by Django 4.0.3 on 2026-03-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('parish', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='Portugal', max_length=100)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'customer addresses',
            },
        ),
    ]
