# Generated by Django 4.0.3 on 2026-03-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
