# Generated by Django 5.2.11 on 2026-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_iban_customer_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='decisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
