# Generated by Django 5.2.11 on 2026-04-18 10:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='search_vector',
            field=models.GeneratedField(db_comment='tsvector over name/company/nif/email/phone, accent-insensitive.', db_persist=True, expression=django.db.models.expressions.RawSQL("setweight(to_tsvector('simple', public.immutable_unaccent(coalesce(name, ''))), 'A') || setweight(to_tsvector('simple', public.immutable_unaccent(coalesce(company, ''))), 'A') || setweight(to_tsvector('simple', public.immutable_unaccent(coalesce(nif, ''))), 'A') || setweight(to_tsvector('simple', public.immutable_unaccent(coalesce(email, ''))), 'B') || setweight(to_tsvector('simple', public.immutable_unaccent(coalesce(phone, ''))), 'B')", params=()), output_field=django.contrib.postgres.search.SearchVectorField(null=True)),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='search_vector',
            field=models.GeneratedField(db_comment='tsvector over street/municipality/parish/postal_code, accent-insensitive.', db_persist=True, expression=django.db.models.expressions.RawSQL("setweight(to_tsvector('simple', public.immutable_unaccent(coalesce(street, ''))), 'C') || setweight(to_tsvector('simple', public.immutable_unaccent(coalesce(municipality, ''))), 'C') || setweight(to_tsvector('simple', public.immutable_unaccent(coalesce(parish, ''))), 'C') || setweight(to_tsvector('simple', public.immutable_unaccent(coalesce(postal_code, ''))), 'C')", params=()), output_field=django.contrib.postgres.search.SearchVectorField(null=True)),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='customers_c_search__377206_gin'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='customers_c_search__ee101b_gin'),
        ),
    ]
