# Generated by Django 5.2.11 on 2026-06-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_search_vector_customeraddress_search_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('cc_cidadao', models.CharField(blank=True, default='', max_length=50)),
                ('nif', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegacyImportMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=32)),
                ('legacy_id', models.IntegerField()),
                ('object_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'legacy_id'], name='customers_l_entity_9961da_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity', 'legacy_id'), name='uniq_legacy_entity_id')],
            },
        ),
    ]
