# Generated by Django 4.0.3 on 2026-02-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acesso', models.CharField(max_length=100)),
                ('tarifario', models.CharField(max_length=100)),
                ('operadora', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moeda', models.CharField(choices=[('EUR', 'Euro')], default='EUR', max_length=3)),
                ('conta', models.CharField(max_length=100)),
                ('cvp', models.CharField(max_length=100)),
                ('data_fim', models.DateField()),
                ('num_client', models.CharField(max_length=100)),
                ('num_servico', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customers.customer')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.customerservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
