# Generated by Django 5.2.11 on 2026-04-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_customerservice_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='morada',
            field=models.TextField(blank=True, default=''),
        ),
    ]
