# Generated by Django 5.2.11 on 2026-04-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SERVICO', 'Serviço')], max_length=32)),
                ('subtype', models.CharField(choices=[('SERVICO_A_TERMINAR', 'Serviço a terminar')], max_length=64)),
                ('metadata', models.JSONField()),
                ('dedup_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'dismissed_at', 'created_at'], name='notificatio_is_read_ae225d_idx')],
            },
        ),
    ]
